models:
    - task: question_answering
      model_path: zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned80_quant-none-vnni
      batch_size: 1
      kwargs:
        sequence_length: 384
integration: sagemaker
