num_cores: 1
num_workers: 1
integration: sagemaker
endpoints:
    - task: question_answering
      route: /invocations
      model: zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned90-none
      batch_size: 1
      bucketing:
        sequence_lengths: [128]
