{
 "title": "Tutorial 1 Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src = \"https://neuralmagic.com/wp-content/uploads/2022/02/Neural-Magic-Logo-Horizontal-scaled.jpg\" style=\"height:80%;align=right;\"/>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 7, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:500%; font-weight: bold; color: #C8D200;\"> DeepSparse Server </p>\n"
   }
  },
  {
   "title": "Number of request processed",
   "type": "stat",
   "description": "The amount of forward passes processed by this pipeline",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "image_classification_pipeline:total_inference_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inference: Mean (over last $interval)",
   "type": "timeseries",
   "description": "Tracks the mean total inference time over the moving window of $interval minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expression": "$rate_sum * 1000/$rate_count\n", "type": "math" }
   ]
  },
  {
   "title": "Total Inference: Histogram of latencies",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "image_classification_pipeline:total_inference_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}