twitter_tokens:
    consumer_key: "4UsAbnrjATJIrLiREGRNtzx2J"
    consumer_secret: "DOBei4FGtHDTqWrllxUh0wYMaudDstAqRf6xv27vl2PhUCAIw9"
    access_token: "970498980403712000-NGL03wNmTHwhJWW5jyq6i84IL1dTbM9"
    access_token_secret: "AplcDj4LJI0DisTUpg5OBXCVWge54HC9jSPWD9KpZnxDI"