consumer_key: "ktsgEVbO3anzFTTnnJxufjO9I"
consumer_secret: "9DSuGpJzphAHsOdMG5UDKCJ7Qalczph96a4DIaPuFTyG2QzFkx"
access_token: "970498980403712000-54k2rcmdahLbUWtJaxcspsBfCpxGle8"
access_token_secret: "0fczmYl6JF6abHyBjFHItB9g4hN2RPvxS1Zs5ox3WubeB"

task: "text-classification"
sent_model: "zoo:nlp/sentiment_analysis/bert-base/pytorch/huggingface/sst2/12layer_pruned80_quant-none-vnni"
task: "text-classification"
topic_model: "zoo:nlp/sentiment_analysis/bert-base/pytorch/huggingface/sst2/12layer_pruned80_quant-none-vnni"