name: Build and Publish Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    name: Build and Push Version Tagged Docker Images to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Github Packages
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Tag
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF_NAME#*/})"

      - name: Current Version Name
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        run: |
          echo ${{ steps.extract_tag.outputs.tag }}

      - name: Build and  push deepsparse with all dependencies
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=all
            VERSION=${{ steps.extract_tag.outputs.tag }}
          push: true
          tags: |
            ghcr.io/neuralmagic/deepsparse:${{ steps.extract_tag.outputs.tag }}

      - name: Build and push deepsparse-base
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=base
            VERSION=${{ steps.extract_tag.outputs.tag }}
          push: true
          tags: |
            ghcr.io/neuralmagic/deepsparse-base:${{ steps.extract_tag.outputs.tag }}


      - name: Image digest
        if: ${{ contains(github.ref, 'refs/heads/release/') }}
        run: echo ${{ steps.docker_build.outputs.digest }}
